import SwiftUI

extension AppTheme {
    static let arcade = AppTheme(
        id: "arcade",
        displayName: "Arcade",
        icon: "gamecontroller.fill",
        colors: ThemeColors(
            background: Color(red: 0.06, green: 0.06, blue: 0.18),
            surface: Color(red: 0.10, green: 0.10, blue: 0.24),
            surfaceBorder: Color(red: 0.0, green: 1.0, blue: 0.0).opacity(0.5),
            running: Color(red: 0.0, green: 1.0, blue: 0.0),
            walking: Color(red: 1.0, green: 0.67, blue: 0.0),
            heartRate: Color(red: 1.0, green: 0.0, blue: 0.0),
            steps: Color(red: 0.0, green: 0.67, blue: 1.0),
            calories: Color(red: 1.0, green: 0.33, blue: 0.0),
            stationary: Color(red: 0.53, green: 0.53, blue: 0.67),
            cycling: Color(red: 0.0, green: 0.67, blue: 1.0),
            swimming: Color(red: 0.0, green: 1.0, blue: 1.0),
            hiking: Color(red: 1.0, green: 0.67, blue: 0.0),
            elliptical: Color(red: 1.0, green: 0.0, blue: 1.0),
            crossTraining: Color(red: 1.0, green: 1.0, blue: 0.0),
            ctaPrimary: Color(red: 0.0, green: 1.0, blue: 0.0),
            ctaDestructive: Color(red: 1.0, green: 0.0, blue: 0.0),
            ctaWarning: Color(red: 1.0, green: 0.67, blue: 0.0),
            ctaPause: Color(red: 1.0, green: 1.0, blue: 0.0),
            iconOnCTA: Color(red: 0.06, green: 0.06, blue: 0.18),
            hrZone1: Color(red: 0.0, green: 0.67, blue: 1.0),
            hrZone2: Color(red: 0.0, green: 1.0, blue: 0.0),
            hrZone3: Color(red: 1.0, green: 1.0, blue: 0.0),
            hrZone4: Color(red: 1.0, green: 0.67, blue: 0.0),
            hrZone5: Color(red: 1.0, green: 0.0, blue: 0.0),
            stepWork: Color(red: 0.0, green: 1.0, blue: 0.0),
            stepRest: Color(red: 1.0, green: 0.67, blue: 0.0),
            stepWarmup: Color(red: 0.0, green: 0.67, blue: 1.0),
            stepCooldown: Color(red: 0.0, green: 0.67, blue: 1.0),
            pace: Color(red: 1.0, green: 0.0, blue: 1.0),
            positive: Color(red: 0.0, green: 1.0, blue: 0.0),
            negative: Color(red: 1.0, green: 0.67, blue: 0.0),
            recoveryFresh: Color(red: 0.0, green: 1.0, blue: 0.0),
            recoveryNormal: Color(red: 0.0, green: 0.67, blue: 1.0),
            recoveryFatigued: Color(red: 1.0, green: 0.67, blue: 0.0),
            recoveryOverreaching: Color(red: 1.0, green: 0.0, blue: 0.0),
            paceInterval: Color(red: 1.0, green: 0.0, blue: 0.0),
            paceThreshold: Color(red: 1.0, green: 0.67, blue: 0.0),
            paceTempo: Color(red: 1.0, green: 1.0, blue: 0.0),
            paceModerate: Color(red: 0.0, green: 1.0, blue: 0.0),
            paceEasy: Color(red: 0.0, green: 0.67, blue: 1.0),
            textPrimary: .white,
            textSecondary: Color(red: 0.53, green: 0.53, blue: 0.67),
            cardBackground: Color(red: 0.10, green: 0.10, blue: 0.24),
            watchCardBackground: Color(red: 0.10, green: 0.10, blue: 0.24),
            watchButtonBackground: Color(red: 0.15, green: 0.15, blue: 0.30)
        ),
        fonts: ThemeFonts(
            timerDisplay: .system(.largeTitle, design: .monospaced).weight(.heavy),
            metricLarge: .system(.title2, design: .rounded).weight(.heavy),
            metricMedium: .system(.body, design: .rounded).weight(.bold),
            metricSmall: .system(.callout, design: .rounded).weight(.bold),
            cardTitle: .system(.headline, design: .rounded).weight(.heavy),
            cardSubtitle: .system(.subheadline, design: .rounded).weight(.semibold),
            cardCaption: .system(.caption, design: .rounded).weight(.medium),
            sectionHeader: .system(.headline, design: .rounded).weight(.heavy),
            heroIcon: .system(size: 32, weight: .heavy),
            onboardingIcon: .system(size: 48, weight: .heavy),
            prValue: .system(.title3, design: .rounded).weight(.heavy),
            microLabel: .system(size: 9, weight: .bold, design: .monospaced),
            debugMono: .system(.caption, design: .monospaced),
            watchTimerDisplay: .system(size: 36, weight: .heavy, design: .monospaced),
            watchMetricDisplay: .system(size: 40, weight: .heavy, design: .rounded),
            watchMetricSecondary: .system(size: 22, weight: .bold, design: .rounded),
            watchStepLabel: .system(size: 13, weight: .heavy),
            watchControlIcon: .system(size: 26, weight: .bold),
            watchControlLabel: .system(size: 11, weight: .bold),
            watchStatusBadge: .system(size: 13, weight: .heavy),
            watchSummaryTimer: .system(.title, design: .monospaced).weight(.heavy),
            watchSummaryMetric: .system(.body, design: .rounded).weight(.bold),
            watchHeroIcon: .system(size: 32, weight: .heavy),
            watchHeroTitle: .system(.title3, design: .rounded).weight(.heavy),
            watchTemplateTitle: .system(.body, design: .rounded).weight(.bold)
        ),
        effects: ThemeEffects(
            cardStyle: .pixel,
            hasNeonGlow: false,
            hasScanlines: false,
            hasGridBackground: false,
            neonGlowColor: nil,
            cardCornerRadius: 4,
            buttonCornerRadius: 4,
            hasMeshBackground: false,
            hasHorizonGrid: false,
            hasLCDDotMatrix: false,
            hasCRTEffect: true,
            cardAccentBarWidth: 0
        )
    )
}
