import SwiftUI

extension AppTheme {
    static let casio = AppTheme(
        id: "casio",
        displayName: "Casio LCD",
        icon: "clock.fill",
        colors: ThemeColors(
            background: Color(red: 0.05, green: 0.05, blue: 0.05),
            surface: Color(red: 0.10, green: 0.10, blue: 0.10),
            surfaceBorder: Color(red: 0.20, green: 0.20, blue: 0.20),
            running: Color(red: 0.22, green: 1.0, blue: 0.08),
            walking: Color(red: 1.0, green: 0.72, blue: 0.0),
            heartRate: Color(red: 1.0, green: 0.20, blue: 0.20),
            steps: Color(red: 0.22, green: 1.0, blue: 0.08),
            calories: Color(red: 1.0, green: 0.72, blue: 0.0),
            stationary: Color(red: 0.40, green: 0.40, blue: 0.40),
            cycling: Color(red: 0.22, green: 1.0, blue: 0.08),
            swimming: Color(red: 0.0, green: 0.80, blue: 0.80),
            hiking: Color(red: 1.0, green: 0.72, blue: 0.0),
            elliptical: Color(red: 0.22, green: 1.0, blue: 0.08),
            crossTraining: Color(red: 1.0, green: 0.72, blue: 0.0),
            ctaPrimary: Color(red: 0.22, green: 1.0, blue: 0.08),
            ctaDestructive: Color(red: 1.0, green: 0.20, blue: 0.20),
            ctaWarning: Color(red: 1.0, green: 0.72, blue: 0.0),
            ctaPause: Color(red: 1.0, green: 0.72, blue: 0.0),
            iconOnCTA: Color(red: 0.05, green: 0.05, blue: 0.05),
            hrZone1: Color(red: 0.22, green: 1.0, blue: 0.08),
            hrZone2: Color(red: 0.22, green: 1.0, blue: 0.08),
            hrZone3: Color(red: 1.0, green: 0.72, blue: 0.0),
            hrZone4: Color(red: 1.0, green: 0.50, blue: 0.0),
            hrZone5: Color(red: 1.0, green: 0.20, blue: 0.20),
            stepWork: Color(red: 0.22, green: 1.0, blue: 0.08),
            stepRest: Color(red: 1.0, green: 0.72, blue: 0.0),
            stepWarmup: Color(red: 0.22, green: 1.0, blue: 0.08),
            stepCooldown: Color(red: 0.22, green: 1.0, blue: 0.08),
            pace: Color(red: 1.0, green: 0.72, blue: 0.0),
            positive: Color(red: 0.22, green: 1.0, blue: 0.08),
            negative: Color(red: 1.0, green: 0.72, blue: 0.0),
            recoveryFresh: Color(red: 0.22, green: 1.0, blue: 0.08),
            recoveryNormal: Color(red: 0.22, green: 1.0, blue: 0.08),
            recoveryFatigued: Color(red: 1.0, green: 0.72, blue: 0.0),
            recoveryOverreaching: Color(red: 1.0, green: 0.20, blue: 0.20),
            paceInterval: Color(red: 1.0, green: 0.20, blue: 0.20),
            paceThreshold: Color(red: 1.0, green: 0.72, blue: 0.0),
            paceTempo: Color(red: 1.0, green: 0.72, blue: 0.0),
            paceModerate: Color(red: 0.22, green: 1.0, blue: 0.08),
            paceEasy: Color(red: 0.22, green: 1.0, blue: 0.08),
            textPrimary: Color(red: 0.67, green: 0.67, blue: 0.67),
            textSecondary: Color(red: 0.40, green: 0.40, blue: 0.40),
            cardBackground: Color(red: 0.10, green: 0.10, blue: 0.10),
            watchCardBackground: Color(red: 0.10, green: 0.10, blue: 0.10),
            watchButtonBackground: Color(red: 0.15, green: 0.15, blue: 0.15)
        ),
        fonts: ThemeFonts(
            timerDisplay: .system(.largeTitle, design: .monospaced).weight(.bold),
            metricLarge: .system(.title2, design: .monospaced).weight(.bold),
            metricMedium: .system(.body, design: .monospaced).weight(.semibold),
            metricSmall: .system(.callout, design: .monospaced).weight(.medium),
            cardTitle: .system(.headline, design: .monospaced).weight(.bold),
            cardSubtitle: .system(.subheadline, design: .monospaced),
            cardCaption: .system(.caption, design: .monospaced),
            sectionHeader: .system(.headline, design: .monospaced).weight(.bold),
            heroIcon: .system(size: 32, weight: .medium),
            onboardingIcon: .system(size: 48),
            prValue: .system(.title3, design: .monospaced).weight(.bold),
            microLabel: .system(size: 9, design: .monospaced),
            debugMono: .system(.caption, design: .monospaced),
            watchTimerDisplay: .system(size: 40, weight: .bold, design: .monospaced),
            watchMetricDisplay: .system(size: 40, weight: .bold, design: .monospaced),
            watchStepLabel: .system(size: 13, weight: .bold, design: .monospaced),
            watchControlIcon: .system(size: 26, weight: .semibold),
            watchControlLabel: .system(size: 11, design: .monospaced),
            watchStatusBadge: .system(size: 13, weight: .bold, design: .monospaced),
            watchSummaryTimer: .system(.title, design: .monospaced).weight(.bold),
            watchSummaryMetric: .system(.body, design: .monospaced).weight(.semibold),
            watchHeroIcon: .system(size: 32, weight: .medium),
            watchHeroTitle: .system(.title3, design: .monospaced).weight(.semibold),
            watchTemplateTitle: .system(.body, design: .monospaced).weight(.semibold)
        ),
        effects: ThemeEffects(
            cardStyle: .lcd,
            hasNeonGlow: false,
            hasScanlines: true,
            hasGridBackground: false,
            neonGlowColor: nil,
            cardCornerRadius: 8,
            buttonCornerRadius: 8,
            hasMeshBackground: false,
            hasHorizonGrid: false,
            hasLCDDotMatrix: true,
            hasCRTEffect: false
        )
    )
}
