import SwiftUI

extension AppTheme {
    static let synthwave = AppTheme(
        id: "synthwave",
        displayName: "Synthwave",
        icon: "sun.horizon.fill",
        colors: ThemeColors(
            background: Color(red: 0.04, green: 0.04, blue: 0.10),
            surface: Color(red: 0.08, green: 0.08, blue: 0.16),
            surfaceBorder: Color(red: 0.0, green: 0.96, blue: 1.0).opacity(0.3),
            running: Color(red: 0.22, green: 1.0, blue: 0.08),
            walking: Color(red: 1.0, green: 0.72, blue: 0.0),
            heartRate: Color(red: 1.0, green: 0.18, blue: 0.58),
            steps: Color(red: 0.0, green: 0.96, blue: 1.0),
            calories: Color(red: 1.0, green: 0.42, blue: 0.61),
            stationary: Color(red: 0.48, green: 0.48, blue: 0.60),
            cycling: Color(red: 0.0, green: 0.96, blue: 1.0),
            swimming: Color(red: 0.29, green: 0.57, blue: 1.0),
            hiking: Color(red: 1.0, green: 0.72, blue: 0.0),
            elliptical: Color(red: 0.71, green: 0.30, blue: 1.0),
            crossTraining: Color(red: 1.0, green: 0.42, blue: 0.61),
            ctaPrimary: Color(red: 0.0, green: 0.96, blue: 1.0),
            ctaDestructive: Color(red: 1.0, green: 0.18, blue: 0.58),
            ctaWarning: Color(red: 1.0, green: 0.72, blue: 0.0),
            ctaPause: Color(red: 1.0, green: 0.72, blue: 0.0),
            iconOnCTA: Color(red: 0.04, green: 0.04, blue: 0.10),
            hrZone1: Color(red: 0.29, green: 0.57, blue: 1.0),
            hrZone2: Color(red: 0.22, green: 1.0, blue: 0.08),
            hrZone3: Color(red: 1.0, green: 0.72, blue: 0.0),
            hrZone4: Color(red: 1.0, green: 0.42, blue: 0.0),
            hrZone5: Color(red: 1.0, green: 0.18, blue: 0.58),
            stepWork: Color(red: 0.22, green: 1.0, blue: 0.08),
            stepRest: Color(red: 1.0, green: 0.72, blue: 0.0),
            stepWarmup: Color(red: 0.0, green: 0.96, blue: 1.0),
            stepCooldown: Color(red: 0.71, green: 0.30, blue: 1.0),
            pace: Color(red: 0.71, green: 0.30, blue: 1.0),
            positive: Color(red: 0.22, green: 1.0, blue: 0.08),
            negative: Color(red: 1.0, green: 0.42, blue: 0.0),
            recoveryFresh: Color(red: 0.22, green: 1.0, blue: 0.08),
            recoveryNormal: Color(red: 0.0, green: 0.96, blue: 1.0),
            recoveryFatigued: Color(red: 1.0, green: 0.72, blue: 0.0),
            recoveryOverreaching: Color(red: 1.0, green: 0.18, blue: 0.58),
            paceInterval: Color(red: 1.0, green: 0.18, blue: 0.58),
            paceThreshold: Color(red: 1.0, green: 0.42, blue: 0.0),
            paceTempo: Color(red: 1.0, green: 0.72, blue: 0.0),
            paceModerate: Color(red: 0.22, green: 1.0, blue: 0.08),
            paceEasy: Color(red: 0.0, green: 0.96, blue: 1.0),
            textPrimary: Color(red: 0.88, green: 0.88, blue: 0.88),
            textSecondary: Color(red: 0.48, green: 0.48, blue: 0.60),
            cardBackground: Color(red: 0.08, green: 0.08, blue: 0.16),
            watchCardBackground: Color(red: 0.08, green: 0.08, blue: 0.16),
            watchButtonBackground: Color(red: 0.12, green: 0.12, blue: 0.22)
        ),
        fonts: ThemeFonts(
            timerDisplay: .system(.largeTitle, design: .monospaced).weight(.bold),
            metricLarge: .system(.title2, design: .monospaced).weight(.bold),
            metricMedium: .system(.body, design: .monospaced).weight(.semibold),
            metricSmall: .system(.callout, design: .monospaced).weight(.medium),
            cardTitle: .system(.headline, design: .default).weight(.bold),
            cardSubtitle: .subheadline,
            cardCaption: .caption,
            sectionHeader: .system(.headline, design: .default).weight(.bold),
            heroIcon: .system(size: 32, weight: .medium),
            onboardingIcon: .system(size: 48),
            prValue: .system(.title3, design: .monospaced).weight(.bold),
            microLabel: .system(size: 9, design: .monospaced),
            debugMono: .system(.caption, design: .monospaced),
            watchTimerDisplay: .system(size: 40, weight: .bold, design: .monospaced),
            watchMetricDisplay: .system(size: 40, weight: .bold, design: .monospaced),
            watchStepLabel: .system(size: 13, weight: .bold),
            watchControlIcon: .system(size: 26, weight: .semibold),
            watchControlLabel: .system(size: 11),
            watchStatusBadge: .system(size: 13, weight: .bold),
            watchSummaryTimer: .system(.title, design: .monospaced).weight(.bold),
            watchSummaryMetric: .system(.body, design: .monospaced).weight(.semibold),
            watchHeroIcon: .system(size: 32, weight: .medium),
            watchHeroTitle: .system(.title3, design: .default).weight(.semibold),
            watchTemplateTitle: .system(.body, design: .default).weight(.semibold)
        ),
        effects: ThemeEffects(
            cardStyle: .neon,
            hasNeonGlow: true,
            hasScanlines: false,
            hasGridBackground: false,
            neonGlowColor: Color(red: 0.0, green: 0.96, blue: 1.0),
            cardCornerRadius: 12,
            buttonCornerRadius: 12
        )
    )
}
