import SwiftUI

extension AppTheme {
    static let clean = AppTheme(
        id: "clean",
        displayName: "Clean",
        icon: "sparkles",
        colors: ThemeColors(
            background: Color(.systemBackground),
            surface: Color(.secondarySystemBackground),
            surfaceBorder: Color.clear,
            running: .green,
            walking: .orange,
            heartRate: .red,
            steps: .blue,
            calories: .orange,
            stationary: .secondary,
            cycling: .blue,
            swimming: .cyan,
            hiking: .brown,
            elliptical: .purple,
            crossTraining: .indigo,
            ctaPrimary: .green,
            ctaDestructive: .red,
            ctaWarning: .orange,
            ctaPause: .yellow,
            iconOnCTA: .black,
            hrZone1: .blue,
            hrZone2: .green,
            hrZone3: .yellow,
            hrZone4: .orange,
            hrZone5: .red,
            stepWork: .green,
            stepRest: .orange,
            stepWarmup: .blue,
            stepCooldown: .blue,
            pace: .purple,
            positive: .green,
            negative: .orange,
            recoveryFresh: .green,
            recoveryNormal: .blue,
            recoveryFatigued: .orange,
            recoveryOverreaching: .red,
            paceInterval: .red,
            paceThreshold: .orange,
            paceTempo: .yellow,
            paceModerate: .green,
            paceEasy: .blue,
            textPrimary: Color(.label),
            textSecondary: Color(.secondaryLabel),
            cardBackground: Color(.secondarySystemBackground),
            watchCardBackground: Color.white.opacity(0.12),
            watchButtonBackground: Color.white.opacity(0.15)
        ),
        fonts: ThemeFonts(
            timerDisplay: .system(.largeTitle, design: .monospaced).weight(.semibold),
            metricLarge: .system(.largeTitle, design: .rounded).weight(.bold),
            metricMedium: .system(.title2, design: .rounded).weight(.semibold),
            metricSmall: .system(.body, design: .rounded).weight(.medium),
            cardTitle: .headline,
            cardSubtitle: .subheadline,
            cardCaption: .caption,
            sectionHeader: .headline,
            heroIcon: .system(size: 48),
            onboardingIcon: .system(size: 72),
            prValue: .system(.title3, design: .rounded).weight(.bold),
            microLabel: .system(size: 9),
            debugMono: .system(.caption, design: .monospaced),
            watchTimerDisplay: .system(size: 40, weight: .bold, design: .monospaced),
            watchMetricDisplay: .system(size: 40, weight: .bold, design: .rounded),
            watchStepLabel: .system(size: 13, weight: .bold),
            watchControlIcon: .system(size: 26, weight: .semibold),
            watchControlLabel: .system(size: 11),
            watchStatusBadge: .system(size: 13, weight: .bold),
            watchSummaryTimer: .system(.title, design: .monospaced).weight(.bold),
            watchSummaryMetric: .system(.body, design: .rounded).weight(.semibold),
            watchHeroIcon: .system(size: 32, weight: .medium),
            watchHeroTitle: .system(.title3, design: .rounded).weight(.semibold),
            watchTemplateTitle: .system(.body, design: .rounded).weight(.semibold)
        ),
        effects: ThemeEffects(
            cardStyle: .glass,
            hasNeonGlow: false,
            hasScanlines: false,
            hasGridBackground: false,
            neonGlowColor: nil,
            cardCornerRadius: 16,
            buttonCornerRadius: 14,
            hasMeshBackground: true,
            hasHorizonGrid: false,
            hasLCDDotMatrix: false,
            hasCRTEffect: false
        )
    )
}
